{
 "title": "Fibertel status",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Fibertel TX Power",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    { "expr": "fibertel_tx_pwr", "legendFormat": "TX Power" }
   ]
  },
  {
   "title": "Fibertel RX Power",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    { "expr": "fibertel_rx_pwr", "legendFormat": "RX Power" }
   ]
  },
  {
   "title": "Fibertel MER Power",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    { "expr": "fibertel_mer", "legendFormat": "MER Power" }
   ]
  }
 ]
}